### ISSUE TITLE
Adjusted prevalence shows 0.00%

### ISSUE THREAD

**Issue by blanchardjeremy** [microCOVID/microCOVID#1247]
Seems like a serious issue.

https://www.microcovid.org/?distance=sixFt&duration=120&interaction=oneTime&personCount=3&riskProfile=hasCovid&scenarioName=custom&setting=indoor&subLocation=US_06001&theirMask=basic&topLocation=US_06&voice=normal&yourMask=basic

![image](https://user-images.githubusercontent.com/32290/146022183-d76d1461-c376-403e-a10b-a45833eb6f9e.png)

I think it is showing 0 for every single location. I checked 5 or so. 

I wonder if we could also add some tests for this so the script doesn't merge a prevalence update that breaks everything.

**Comment by cmounce** [comment]
Looks like it started happening because the prevalence update started including its own `updatedAt` with a bad date format. The JS code doesn't actually need the new `updatedAt`, so [I opened a PR that temporarily prunes it out](https://github.com/microCOVID/microCOVID/pull/1248). Seems to fix the issue on my local machine, at least.

**Comment by chrisvfritz** [comment]
Until a working build is deployed, folks can see use the last working version here:

https://web.archive.org/web/20211214032440/https://www.microcovid.org/[https://web.archive.org/web/20211214032440/https://www.microcovid.org/](https://web.archive.org/web/20211214032440/https://www.microcovid.org/)

**Comment by oxytocinlove** [comment]
should be fixed as of the next automated prevalence update
