### ISSUE TITLE
P100, Their mask, very low protection ?!

### ISSUE THREAD

**Issue by 1000i100** [microCOVID/microCOVID#1287]
**Describe the bug**
For "Your Mask", P100 offer the best protection.
For "Their Mask", P100 offer a very low protection compared to N95 of FFP2

I see : unclear if outflow valve is covered for their mask and with covered outflow valve for your mask.
Why not including the 2 option in both ? or at least in their mask section ?

**Link to microCOVID scenario**
https://www.microcovid.org/?distance=normal&duration=15&interaction=oneTime&personCount=1&riskProfile=average&scenarioName=1person_15minCarRide&setting=indoor&theirMask=p100&topLocation=France&voice=normal&yourMask=p100

**To Reproduce**
1. Go to https://www.microcovid.org/
2. Click on any senario with mask available and choose P100 for their mask.
3. See error : only 1/3 of risk reduction.

**Expected behavior**
1/30 effect on risk if well-used.

**Is this a regression?**
Don't know

**Additional context / screenshots**
Nop

**Comment by beshaya** [comment]
The current behavior is working as intended. We expect that most people are covering their outflow valves with a piece of cloth or loose fitting surgical mask, for which 1/3 is accurate - the exhaled air is going through cloth, not the P100 filter.

If you actually tape over the valve entirely... well, some P100's have one-way valves for the filters, so you'd be forcing the air out around the mask seal, dropping the effective multiplier to 1. If you *know* that their P100's valve is sealed and the air *is* going out through the filters, then sure, take a 1/30. We don't support this directly because we think its really rare, easy to do wrong, and mask manufacturers don't recommend this as you'll wear out the filter faster and get it wet which makes breathing through it harder. But if you want to do it, please feel empowered to divide the answer by 10 at the end.

The other somewhat common thing among enthusiasts is to cover the outflow valve with N95 filter media, taping it such that air must go through the filter. This would plausibly give 1/16, same as an N95. In that case, you can just say that their mask is an N95 - because that's what's between you and their air.

**Comment by 1000i100** [comment]
Thank you for your quick and detailed answer !
I close the issue ;)
