### ISSUE TITLE
Caution budget type : immunity benchmark

### ISSUE THREAD

**Issue by 1000i100** [microCOVID/microCOVID#1322]
**Is your feature request related to a situation you're trying to understand with microCOVID? Please describe.**
If somebody is not afraid about getting ill with covid, but don't want to transmit it to others, a strategy can be : 
kiss as many COVID positive people as possible during a short duration (1 day, or 1 week), then isolate 7 day or more, cure itself if needed, then consider self as immune for 3 months at least. So safe to see other people without risk of transmitting.

Does this case look valid ?

**Describe the solution you'd like**
Have a risk template focus about getting covid (if you do all what you shouldn't do to avoid covid, with this scenario you have 99,99% chance to have covid if your body can be infected with it).

**Relevant Research or Citations**
Could be helpful to have study about minimal re-infection interval. For example, is there some people who get Delta in last November and get Omicron in December ?

**Comment by 1000i100** [comment]
This look to be a valid senario for this purpose : 
https://www.microcovid.org/?distance=intimate&duration=60&interaction=oneTime&personCount=14&riskBudget=100000&riskProfile=hasCovid&scenarioName=bar&setting=indoor&theirMask=none&topLocation=France&voice=loud&yourMask=none&yourVaccineDoses=2&yourVaccineType=moderna

**Comment by beshaya** [comment]
That strategy makes some sense for 3 months, but what do you do afterwards? After 3-6 months, your immunity would start to wane, so if you want to avoid giving COVID to others you'll be back to being careful before seeing them. I guess you could try to get it every 3 months and assume that, if you fail, you're good for another 3 months, but I haven't seen studies that suggest this would work. Also, having a LOT of people get infected really quickly (what is happening right now) is fairly ideal conditions for creating the next variant that evades immune responses to the current variant.

Also, let's say prior infection gives 99% reduced chances of getting COVID for the next 3 months. Eating at a restaurant in France comes up as 160,000microCOVID, so 99% reduction is still 1,600 microCOVID, which is still higher than really cautious folks tolerate. Is prior infection better than 99% protective for some duration of time? The study I generally cite said 90% over 6 months but didn't break it down by month, probably there's better out there now. 

A similar strategy I've been rolling around in my head is: do more or less what you want, unless you need to be not sick for something in which case be cautious for 2 weeks beforehand. Disclose to others that you're probably higher risk. Don't worry too much about transmitting in public spaces like restaurants, since people going there will get it from someone else if they don't get it from you.

**Comment by tkpwaeub** [comment]
Um, do you really need a mathematical model for this? You can live your life with wild abandon without having to calculate odds of catching Covid. If you're trying to make sure you don't transmit the virus to others, wear a well fitting mask and test yourself regularly. Other people can use this risk assessment tool to decide if it's safe to be around *you*.

**Comment by tkpwaeub** [comment]
It should also be noted that for the scenario in question - close to a million microcovids - the actual probability that you alproach is 1-(1/e) or approximately 63%.
