### ISSUE TITLE
Handle regions with negative daily cases

### ISSUE THREAD

**Issue by Grubla** [microcovid/microcovid#145]
Sweden and most of it's regions have a negative number of "Reported cases in past week". The total numbers for Sweden has declined in the JHU CSSE data, between 8/26 and 8/28 since the historic data has been corrected (the actual cases removed are over the last months, and were called false positives). 

This breaks the calculator and no result or risk level is given. 

![image](https://user-images.githubusercontent.com/1529750/91656502-70c48c80-eab9-11ea-9503-5a6f063f7dbc.png)

**Comment by Grubla** [comment]
I couldn't find any negative numbers from ourworldindata, but I'd be willing to help/investigate if someone points me in the right direction :)

**Comment by oremanj** [comment]
Thanks for the report! We're using JHU CSSE because it was the only source we could find for international data that was finer-grained than an entire country. Unfortunately they don't go back and update their previous "total new cases as of <date>" reports when historical corrections are made, which sometimes leads to issues like this. (Last week it was Massachusetts.)

If you have another source of prevalence data, you can still use the calculator by entering it in the boxes manually. And I bet the negativity will resolve itself when we pull updated data in a week or so. I'm not sure if we'll be able to add the ability to fall back to an alternate data source before then, but I'll update this issue if we do so.

**Comment by oremanj** [comment]
This is resolved in the latest data update. We still don't have a principled solution, but hopefully we won't wind up needing one.
