### ISSUE TITLE
Pull in prevalence estimates from another source rather than rolling our own

### ISSUE THREAD

**Issue by catherio** [microcovid/microcovid#154]
An example might be https://covid19-projections.com/us-ca. We would need to look into their methodology and decide if we like/trust this source.

**Comment by oremanj** [comment]
I just checked California. They think 630,000 people are currently infected, of which half are actively infectious = 315,000. We think there were 38,485 reported cases in the past week, and multiply by 8 to get 307,880 infections. Close enough IMO! For the US as a whole we estimate 2.33 million active infections, relative to their 2.04 million.

I haven't read the full analysis on https://covid19-projections.com/estimating-true-infections/, but if we trust it, we could import their formula: `true-new-daily-infections = daily-confirmed-cases * (16 * (positivity-rate)^(0.5) + 2.5)`

**Comment by psthomas** [comment]
I've been using the covid19-projections data for a [visualization](https://pstblog.com/2020/06/12/covid-prob) and it works pretty well, but it does tend to lag during a new outbreak. I think this is because it minimizes error on the deaths timeseries which is lagged by 20-30 days, then runs the model forward to today. So this will underestimate infections at the beginning of a new outbreak because it's still using "old" parameters. The empirical model you mention above might actually perform better because it's based on more recent test positivity data.

IHME's [estimated infections](https://covid19.healthdata.org) suffer from a similar problem, spot checks I've done continuously underestimate cases during new outbreaks (even though they seem to use [hospitalizations](https://twitter.com/SalomonJA/status/1302767017150169090) as a leading indicator of deaths). This might just be because they don't pull new data into their model as often, but right now their estimate for new infections in [Wisconsin](https://covid19.healthdata.org/united-states-of-america/wisconsin) is 1,320. This is less than the 1,408 confirmed cases yesterday, which is probably a 4-10x undercount because cases are growing rapidly.

Another group that's providing an estimate of prevalence is [cmmid](https://cmmid.github.io/topics/covid19/global_cfr_estimates.html). I don't know enough to evaluate their approach, but this [tool](https://19andme.covid19.mathematica.org/) adapted it to estimate local prevalence. Or you could just keep using your current approach, it seems to [perform well](https://gist.github.com/psthomas/e124d02cbe1658b5d0fedc43b9eae628) when compared to seroprevalence studies, and it probably won't miss new outbreaks because it's based on reported cases. The only concern I have is that the correlation between test positivity and the CAR might not hold if places ramp up their testing capabilities differently.

**Comment by catherio** [comment]
proposal: use the estimates from https://covidestim.org/?

**Comment by jy2wong** [comment]
http://localhost:3000/paper/14-research-sources#basic-method-underreporting-factor we use https://covid19-projections.com/estimating-true-infections-revisited/ now.
