### ISSUE TITLE
FAQ: What if someone got a negative test?

### ISSUE THREAD

**Issue by catherio** [microcovid/microcovid#215]
Just write our current beliefs in Q&A about testing window (4-7 days), and amount of reduction this provides based on false negatives (20%). Talk about our masks-in-house policy.

**Comment by catherio** [comment]
Also add criteria for ending isolations, two negative tests >24 hours apart.

**Comment by blanchardjeremy** [comment]
Yeah, the false-negative rate is ridiculous. We basically removed testing as a part of our toolkit when we were taking a "reduce risk as much as possible" approach. Now that we're moving over to your "pick a reasonable risk range" approach, I suppose testing might have some benefit.

Given the way the false-negative rate changes based on what day you were tested, should that factor into the risk reduction you offer?

[This is the only data](https://www.hopkinsmedicine.org/news/newsroom/news-releases/covid-19-test-that-relies-on-viral-genetic-material-gives-false-negative-results-if-used-too-early-in-those-infected) I've seen on false negatives. Have y'all seen anything else?

**Comment by catherio** [comment]
Upgrading this to p1. Testing is being over-relied-upon and I think saying something about it would help.

**Comment by cstigler** [comment]
Recently did a risk assessment on this for my house, using many of the references @blanchardjeremy shared. Sharing my thinking if it's helpful for y'all (and would love to hear your feedback/critique also if you're willing to share!). [Document writeup is here.](https://docs.google.com/document/d/1LhNMPq7VjM2ahSWsk78QHGVolFGfMl7hoLfmzVM7Pzs/edit)

The basic takeaway I ended up with is that _assuming your contact will self-isolate within 24 hours after showing symptoms_ (which we assume, but you may not), there's not much value in testing. I estimated a 26% risk reduction from a negative PCR result tested 1 day prior to the event, and almost no risk reduction from test results further back (3% risk reduction from test at T-3 days, 2% at T-5, 1% at T-7).

The intuitive reasoning for this is that if contacts will self-isolate soon after showing symptoms, they're likely only contagious and active for about 3-4 days (48-72 hours before showing symptoms, ~24 hours after). Trying to detect them during this time with random testing is nigh impossible. Fully asymptomatic people _may_ be contagious (and not isolating) for longer, but they also appear to be responsible for less transmission.

**Comment by beshaya** [comment]
@cstigler Great writeup!

How does the math change if we factor in asymptomatic people being 50-70% as infectious as symptomatic? That appears to be the aggregate of https://www.medrxiv.org/content/10.1101/2020.05.10.20097543v2.full.pdf

**Comment by cstigler** [comment]
@beshaya The current analysis is based on the claim in [this paper](https://science.sciencemag.org/content/368/6491/eabb6936) (found by @blanchardjeremy) that only ~6% of infections are sourced from asymptomatic people (despite [~40-45% of infected people being asymptomatic](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7281624/)). So I've just weighted the symptomatic case to 94% and asymptomatic to 6%.

If we wanted to take the linked paper into account to adjust that weighting, I think we'd need to factor in two pieces of data from it:
- the relative asymptomatic transmission rate - I only skimmed the paper but missed where you found the 50-70% number? I see a table of relative secondary transmission rates with values `0.79`, `0.0`, `0.06`, and `0.0`, which tells me that... the data varies wildly 😛 but I'll assume I just missed the number you're referring to
- the % of cases that are asymptomatic, which this paper estimates at `15% (95% CI: 12% - 18%) overall` - much lower than the 40-45% suggested above

I think the overall weighting wouldn't change much if we assumed 50% relative asymptomatic transmission rate and 15% of cases being asymptomatic, because those two adjustments would nearly cancel each other out. The overall asymptomatic weighting to ~7.5%, which is close enough to the current 6% that I don't think it matters much. Curious if that makes sense to you!

**Comment by beshaya** [comment]
> the relative asymptomatic transmission rate - I only skimmed the paper but missed where you found the 50-70% number? I see a table of relative secondary transmission rates with values 0.79, 0.0, 0.06, and 0.0, which tells me that... the data varies wildly 😛 but I'll assume I just missed the number you're referring to

I got the secondary transmission rate by summing the number of cases from those 4 studies.

I totally missed the total proportion of asymptomatic cases, though! That makes me feel a lot better.

**Comment by jy2wong** [comment]
https://www.microcovid.org/blog/negativetests
