### ISSUE TITLE
Consider disallowing "Cuddling / intimate" distance when outdoors

### ISSUE THREAD

**Issue by ddfisher** [microcovid/microcovid#265]
Currently, the calculator considers cuddling to be 20x safer outdoors than indoors, but the research section notes that there's no data about this distance:
> We feel good about calling [the outside risk reduction] “more than 20x” for now and waiting for more evidence, with a warning about not trusting this number if you’re very close to one another because we have no data about outdoor cuddling.

The current behavior is probably misleading. Given the absence of data, perhaps the "Cuddling / intimate" distance shouldn't be allowed when outdoors?

**Comment by blanchardjeremy** [comment]
Makes sense to me.

**Comment by mattbell** [comment]
I support this in principle, but I want to make sure users understand what is happening, so I think we'd want to pop up a message when you select "cuddling/intimate" that say "Due to the very close distances involved, we are not confident that being outdoors reduces the risk in a substantial way.  Thus, to be conservative, we are not providing any bonus for being outdoors when cuddling/intimate.

**Comment by beshaya** [comment]
Ooh, maybe we need to break apart "cuddling" and "intimate"

I agree that getting your face in someone's face ("intimate") probably doesn't matter if you're inside or outside, but not sure on the "cuddling" side. If you're hugging you aren't breathing directly into each other, if your head is in someone's lap that's 3 feet. 

From a harm reduction standpoint, it's probably better to encourage activities to happen outside if there's a reason to think they're safer that way.

**Comment by autumnsault** [comment]
Perhaps the cuddling/intimate terminology is too vague and there should be a selection for "fluid exchange."

**Comment by raindrift** [comment]
I think being overt in this instance is probably warranted.

But in the meantime, calculating contact indoors vs outdoors using the factors for indoors is probably the safe choice. Otherwise I think it might be under-rating it by quite a lot. I'd hate for people to assume that as long as they're outside, kissing is a low-risk activity.

**Comment by catherio** [comment]
Users are confused by this: https://twitter.com/broabprobe/status/1313318849769504768

I'm in favor of Matt Bell's suggestion

**Comment by catherio** [comment]
I don't mind removing the word "cuddling" and just saying "intimate" if that helps cc @beshaya

**Comment by raindrift** [comment]
I don’t think that’s enough. For many (most?) people “intimate” implies
“hookup”. For it to make sense, it needs to score indoor and outdoor as
being at least approximately the same; certainly within the same order of
magnitude.

It might help to change the wording to “cuddling” but I think that’s still
pretty open to misinterpretation. This is especially true since I think the
comparative risk of a hookup is what many users are actually looking to
determine.

**Comment by beshaya** [comment]
![image](https://user-images.githubusercontent.com/5877421/95175118-d9b1bb00-076f-11eb-9fd5-b6016f20eab3.png)

**Comment by blanchardjeremy** [comment]
Seeing the draft of this in #305, I'm wondering if we're actually doing a disservice by removing cuddling. 

I agree cuddling is ambiguous. And in my understanding, "my face is basically right next to your face" and "we're making out" are roughly the same risk (as far as our model is concerned, anyway). Is that right? 

If so, I wonder if we might call it "Intimate / kissing".

What do you think?

**Comment by autumnsault** [comment]
I like intimate/kissing better than intimate. I don't like using euphemisms in safety conversations. Intimacy may mean sexual activity to most people, but that isn't universal, and it's probably cultural.

**Comment by beshaya** [comment]
Ooof,

How about 
* `Closer than 1 ft` - 12% per hour (backed by research), outdoors doesn't work (speculative)
* `Kissing` - 12% per hour, outdoors doesn't work (speculative but really quite likely), 12% minimum (speculative)

**Comment by beshaya** [comment]
![image](https://user-images.githubusercontent.com/5877421/95262967-f7b80380-07e1-11eb-89a1-66c3cbe537b0.png)

**Comment by blanchardjeremy** [comment]
Thanks for heading this up and working with a ton of people's input, @beshaya
