### ISSUE TITLE
Spreadsheet "Bay Area" population incorrect

### ISSUE THREAD

**Issue by echurilov** [microcovid/microcovid#266]
The spreadsheet lists a population of `881549` under "Bay Area". This this is the population of San Francisco County, _not_ the entire SF Bay Area. The population of the entire Bay Area is more like 7 or 8 million. The header should be updated to reflect that it's SF county, or the population should be corrected.

**Comment by echurilov** [comment]
I've made an [updated version](https://docs.google.com/spreadsheets/d/1p_x-EH3uAeLHdKUs05uWIMIUFigZ5ROjt2U0rhKPhms/edit?usp=sharing) of the spreadsheet that has [NYT prevalence data](https://github.com/nytimes/covid-19-data) for all the Bay Area counties (with positivity rates drawn from the county's official dashboards) plus an aggregate one for the entire Bay Area. I don't know how to make the spreadsheet pull new data, so it still needs manual updating, but I think the prevalence data in this version should be more accurate.

**Comment by echurilov** [comment]
The spreadsheet linked above now pulls new case counts for Bay Area counties daily. The positivity rates still needs manual updating but there are links to each county's official source for those to make it less painful.

**Comment by blanchardjeremy** [comment]
@echurilov brilliant! Useful for bay area folks! I'm not sure that it would make sense to have it be a part of the template spreadsheet since we want it to be easy enough for non-Bay Area folks to use it.

We could get really fancy and import the entire database of prevalence data.  And we could follow your trick of publishing a spreadsheet that gets auto imported by everyone who has cloned the spreadsheet. Making it more user friendly. I'll open a separate issue for that idea.

**Comment by blanchardjeremy** [comment]
Closing this as the latest version uses San Francisco specifically.
