### ISSUE TITLE
Resource intake: Air purifiers

### ISSUE THREAD

**Issue by catherio** [microcovid/microcovid#314]
Can we justify a x6 boost if using a HEPA purifier in the room?

https://www.medrxiv.org/content/10.1101/2020.10.02.20205633v2
https://twitter.com/jljcolorado/status/1313932043009454080

This would also help our overall airplane numbers!! https://github.com/microcovid/microcovid/issues/234

**Comment by beshaya** [comment]
Summary:

Methods:
* Philips Model 2887/10 - standard HEPA filter. 3-4 purifiers were run simultaneously
* Measured using Condensation Particle Counters (TSI, uCPC model 3776) - detection down to 2.5nm
* Room was 186.4 m3
* 5 Windows were open
* 27 students and 1 teacher

Results:
* Opening the windows reduces particle concentration by 30%, with a time constant of 47-71 minutes
* The four purifiers were operated at stage 3 yielding a total volume flow of 1026.4 m3/h and an air exchange rate of 5.5 h-1. The aerosol concentration decreased by more than 95% within 37 minutes
* Time duration matters - "After one hour the difference between the cases with and
without purifiers is a factor of 3.5 and it becomes a factor of 6.2 after 2 hours." (because particle concentration takes time to build up)
![image](https://user-images.githubusercontent.com/5877421/95690836-6a085980-0bcf-11eb-84f7-4ce14b7cbb0d.png)

Takeaways:
* This seems as solid as anything I've seen on masks, with the added bonus that it is robust to various infection routes (eyes vs inhalation.
* The actual flow rate seems critical; the experiment used FOUR purifiers at maximum to circulate the room's worth of air 5 times an hour. I think it's unlikely that many people will have this flow rate. There doesn't seem to be data for lower flow rates.
* This seems most applicable to planes and trains, which may circulate up to [50x per hour](https://www.bart.gov/news/articles/2020/news20200813)
* I find it striking that a 90% decrease in particle count only accounts for a 3-6x decrease in expected case counts. Need to think more about the math behind this.
---
I found this paragraph describing the mechanics of infection to be super interesting - it outlines how much virus a person exhales and how much a person needs to inhale for a 50% chance of infection, applying it to a classroom, and accounts for variation in the population.
>Following the arguments of Lelieveld et al., 2020, we assume an infectious dose D50 of 316 particles as the amount of virus RNA that has to be inhaled by a host to cause an infection with 50% probability. Furthermore, we assume that aerosol particles are deposited in the respiratory system of the host with 50% probability. Breathing and speaking by an infective individual releases 0.06 and 0.6 particles cm-3, respectively, into the exhaled air (Asadi et al., 2019; Stadmytsky et al., 2020; Lelieveld et al., 2020). These assumptions describe rather the case of a super emitter (highly contagious, speaking a lot, emitting a high amount of particles with virus-RNA) compared to a more average case of an infected student that is not
talking for a large fraction of the time. The speaking/breathing ratio is assumed to be 0.1 and the respiration rate per person is 10 liters per minute. We assume the concentration of virus RNA present in the exhaled particles to be 5 x 10^8  per ml for a ‘highly infective’ and 5 109 ml-1 for a ‘super infective’ person (Lelieveld et al., 2020). The particles are exhaled with an average wet diameter of 5 µm when exiting the mouth, but due to the rapid evaporation at lower humidity the particle size quickly reduces to 1-2 µm. The 1/e-lifetime for viable SARS-CoV-2 in aerosol is assumed to be 1,7 hours (van Dormalen et al., 2020). With these assumptions Lelieveld et al., 2020, derive an emission of 68 400 particles per hour from the emitting person and about 3 % of the particles emitted during breathing and speaking contain virus RNA for the highly infective person, and about 30 % contain virus RNA for the super infective one, respectively. For a classroom of 180 m3 volume with a low air exchange rate of 0.35 h-1 and without face masks being used, their model can then be used to calculate a steady-state concentration of RNA-containing aerosol of 0.012 l-1 for the highly infective case and 0.12 l-1 for the super infective case, respectively. For the highly infective case, a susceptible person in the room for 2 hours will take up a dose of 7.6 RNA-containing particles, representing a 1.7% risk of becoming infected. In a room with 25 persons, this leads to an overall risk of
33% that at least one of the other 24 persons becomes infected. For the super infective person with the very high viral load of 5 x 10^9 ml-1 in the emitted particles, the dose acquired in 2 hours changes to 75.9 RNA containing particles, the individual infection risk increases to 15% and the risk that at least one person in the room becomes infected increases to 98%. All the details of the assumptions, parameters and equations used are discussed in Lelieveld et al., 2020.

**Comment by beshaya** [comment]
Also note that the 3-6x is compared to a closed room (no windows or doors open).

**Comment by catherio** [comment]
![image](https://user-images.githubusercontent.com/245037/96496711-6f345c80-11fe-11eb-80ef-b1be603367b3.png)

I'm 👍 to calling this a 4x boost for "HEPA air filter"

**Comment by jeffkaufman** [comment]
As currently implemented, this is a 4X boost if the filter is sufficient to change over all the air in the room five times per hour.  Holding the number of people and the filtration constant, this implies that increasing the volume of the run makes people less safe. This seems pretty unlikely to me?

In the linked study, the room was 27x20 with a 12ft ceiling and 29 people. This is 233 ft^3/person. Their purifier was running at 600 CFM. For extrapolating to larger rooms I think it's probably more accurate to divide 600 CFM by 29 people (27 students, teacher, scientist) and recommend 20 CFM/person?
