### ISSUE TITLE
Thoughts on milliCovid? 

### ISSUE THREAD

**Issue by dandv** [microcovid/microcovid#348]
After playing around with the tool, every time I get a number, I have to make a mental transformation into thousands: "roughly ~2,000-in-a-million" -> "Ok, that's 2 in one thousand...". But more importantly, my *subjective* impression, despite being a software engineer, is that risks are most of the time, very very small. I mean, we're talking about numbers out of *millions*. I wonder if less technical users may subjectively find the risks even lower.

How about expressing the risk as in X-in-a-thousand? `millicovid.org` is also available.

**Comment by blanchardjeremy** [comment]
Thanks for offering ideas. 

If you're doing something that is 2,000 microCOVIDs, we consider that to be VERY high risk. 

We chose microCOVIDs because most people are in the 1-200 range for their activities each week. Millicovids wouldn't do the trick for that range. 

Because of this, I'm closing this one.
