### ISSUE TITLE
Style <Expandable> to have its own background color

### ISSUE THREAD

**Issue by blanchardjeremy** [microCOVID/microCOVID#419]
I think it might be good if they used a "plus" icon rather than a chevron. And the plus icon could float to the right, and the header could be a different background color.

**Comment by oxytocinlove** [comment]
@blanchardjeremy Are you still working on this? Happy to take it over if not!

**Comment by jy2wong** [comment]
aside: "show math" doesn't use the Expandable class, largely because it's not accessible (it gets missed when you try to tab through elements). It would be nice to refactor Expandable so that it's closer to what show math is doing.

Note that "What is a microCOVID?" up in the top little blurb is also an Expandable.

Based on https://www.nngroup.com/articles/accordion-icons/ I would suggest that we stick with carets. (bonus points if you can find a similar study on left-side accordion icons)

I would prefer that none of the existing Expandables (and pseudo-expandables) get significantly different background colours (if different background colours at all). All of them are used for either optional "advanced math-heavy details" or in a distracting place (I think we should aim to keep eye focus on the "HELLO, DELTA VARIANT" alert and where the calculator's interactive elements start).

**Comment by blanchardjeremy** [comment]
Happy to have others take this over! Thanks!
