### ISSUE TITLE
Can't contribute to translations, yet

### ISSUE THREAD

**Issue by comradekingu** [microcovid/microcovid#498]
I translated most of the Weblate resources just now and realized I don't have permissions to do so…
https://hosted.weblate.org/user/kingu/ is the account.
If it is just because of the current reason it is locked,
https://docs.weblate.org/en/latest/admin/continuous.html?highlight=webhook#automatically-receiving-changes-from-github and adding https://github.com/weblate is probably what you want. :)

**Comment by blanchardjeremy** [comment]
@blanchardjeremy thanks so much. 

What language were you translating to?

We were actually only just now trying out weblate and hadn't settled on it as a solution. Did you do the translations inside weblate? Do you have them saved somewhere?

We're also trying out Crowdin as well.

**Comment by comradekingu** [comment]
@blanchardjeremy nb_NO. (Norwegian Bokmål).
Crowdin is COVID-20, in software form. The project is shown in the list of projects one can add from https://hosted.weblate.org/accounts/profile/#notifications
Got the translations open in the Zen editor, hopefully they can be saved once the project opens or permissions are granted.

**Comment by gyp** [comment]
@comradekingu, thanks for contributing!

Weblate is great, but it keeps creating merge conflicts for itself and offers zero way to fix them manually, even if they would be trivial to fix (in 99% of the cases just a simple "use your version" would be the solution). So it sometimes automatically locks itself or I need to do it manually during a merge window.

It's been unlocked since this issue was opened (and locked again, and unlocked again, and so on :)), so this now seems to be moot. Let me know if you still encounter problems.
