### ISSUE TITLE
Remove "delay factor" from prevalence for previous week's activities

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#506]
> Now that we've got automatic location data in the spreadsheet, I'm noticing the whole situation of "my location data got updated, and all the activities I entered in the past week are now way higher" is a bigger problem. I'm thinking through possible solutions, and one of them effects the model, so I'd be curious your thoughts.
Obviously one solution is "copy-paste the row without formulas, then it's exactly the same as it was" is the most accurate. But it's also labor-intensive and requires some spreadsheet skills.
The alternate solution I'm considering right now is: what if we didn't apply the "delay factor" to any line items created before the "location data imported" date?
Example: Alameda County is 0.56% adjusted prevalence right now. The delay factor is 1.55. The data was generated on Nov 11. Is it legit to say that any activity items on Nov 11 or prior could count as actually 0.56%/1.55 = 0.37%?
Obviously, lines prior to the last week are not going to be accurate. But this would at least keep ones in the last 9 days more accurate.  Thoughts?

I already have the format written on my copy of the spreadsheet.

@beshaya said it makes sense

**Comment by beshaya** [comment]
@blanchardjeremy Wait wait wait, I didn't say it made sense. I said your house could do whatever they agreed to, and calculate risk in a less accurate way if it made them happy.

**Comment by blanchardjeremy** [comment]
Oh gotcha. I meant to ask if it also made sense in general. I misunderstood! I'll re open that convo in Slack.

**Comment by beshaya** [comment]
Ack, sorry I totally misunderstood the Issue - I thought you meant removing the 2 day delay for “risk to others” (which I don't support). I do support having previous week's activities use this weeks prevalence with no delay factor correction.

I've updated the description so that this Issue is unambiguous.

**Comment by IWalkInLA** [comment]
This doesn't quite work for the automated prevalence data, but for my household spreadsheet (I live with 6 other professional adults), I solved for the time factor (different dates/locations have different prevalence rates) by moving the prevalence data to a separate sheet, then using a vlookup to compare the date with the location to the correct prevalence data.

**Comment by blanchardjeremy** [comment]
@IWalkInLA Thanks for letting us know. Two questions. 1) what wasn't working with the automated date? 2) could you share how you solved it that way with your house?

**Comment by IWalkInLA** [comment]
1) I adapted the spreadsheet my household uses  from version 1 to address the complaint that the author was having, that the current (v 1 and v2 spreadsheets) only allow for one prevalence rate per location, so anytime it is updated (either manually or automatically), all the calculations use that new prevalence rate; even though it was different on the date that the activity took place. This was an issue for my household because when one of us was planning to do an activity, the prevalence rate was taken into account (For instance, when the prevalence rate was  .38%, our household decided to go to do outdoor dining together whereas when it jumped above 1%, it  was no longer considered safe for the entire group). Otherwise, behavior that had been planned to be safe suddenly would eat up our entire weekly budget. Hence, being able to have a record of the prevalence rate over time has been useful. When the prevalence data changes, it no longer changes the calculations for behaviors earlier in the week with the old prevalence rate, but all new calculations will use the updated prevalence rate. 

2) I don't know how to solve for the automated date/prevalence data, but this was my solution for [manual entry](https://docs.google.com/spreadsheets/d/1gmfN1nvkNW3DmRKDZAi3qm_EjQmvLMUu17bKd2BbV4w/edit#gid=1578369843). 

a) I moved prevalence rates from the Person Risk Facts sheet to the  new Prevalence Risk Facts sheet. Date/Location/Prevalence Rate are recorded there.
b) I updated the formulas on the Person Risk Facts sheet to reflect whether the template person was static or dynamic (affected by the prevalence rate). Those that were affected by the prevalence rate were stripped of the prevalence rate being calculated on that page, as it is now on each housemate's individual sheet. Example: The average frontline worker  is dynamic and is calculated by multiplying the average person x 300%. 
c) On each of our individual sheets, I added columns to the maths section for static/dynamic and the prevalence rate. 
    i. Static/dynamic determines whether the person selected was static or dynamic, so whether or not the prevalence rate should be applied to calculations. 

> _=ISNUMBER(MATCH(E63,PERSON_RISK_FACTS!$B$35:$B$991,0))_

ii.    The prevalence rate uses vlookup to determine what the prevalence rate is for the given date and location of the entry.

> _=IF(F63="Los Angeles", VLOOKUP( C63,PREVALENCE_RISK_FACTS!$B$3:$E$100,3,true),IF(F63="San Diego", VLOOKUP( C63,PREVALENCE_RISK_FACTS!$B$3:$E$100,4,true ),IF(F63="Bay Area", VLOOKUP( C63,PREVALENCE_RISK_FACTS!$B$3:$E$100,2,true ),false)))_

d) I updated the formulas for the existing maths formulas for person risk  (each) to reflect the new columns and calculations. 

> _= VLOOKUP(E63, PERSON_RISK_FACTS!$B$2:$C$946, 2, FALSE)  *IF(G63=true,PERSON_RISK_FACTS!$F$16,1)  *if(T63 = true, 1, S63)_

**Comment by blanchardjeremy** [comment]
Wow.  Impressive. Makes sense. 

Yeah I see the value of what you've done for sure.  It's rarther difficult to make that work with dynamic location data. And I think most users would rather have it be automatic than have their historical data be more precise.

I also like what you've done with the person risk sheet. Interesting to see the various variables and person risk categories your house designed.

**Comment by IWalkInLA** [comment]
I am going to keep playing around with it, to see if I can think of a way to make it work with the dynamic location data, as I agree that with most people, having it automatically updated would probably be useful for more people than having the historical data. 

The historical data has been useful in my household for determining our shortcomings to protocols and better clarifying them for the future. It really helps to have the data to back up changes or concerns.  The focus is always on the specific week, but it is also useful to see trends.

The person risk categories have been a big issue in my household, hence changing them from what appears on spreadsheet v2 document. The template people provided are not as intuitive as I had assumed and it was frustrating to see them being applied incorrectly to the math they were based upon. I tried to clarify them as objectively as possible, so that it would be more accurate. It is still an ongoing issue, though. 

The additional maths are because we are a household with complex relationships, where some are partners and some are not, as well as those with partner(s) outside the house. We have been trying to balance the needs of the introverts with the extroverts, so I have been as transparent as possible for how each of our individual actions/pages could  affect the group as a whole.
