### ISSUE TITLE
Say explicitly that N95 valves should be covered

### ISSUE THREAD

**Issue by oremanj** [microcovid/microcovid#519]
A user wrote in pointing this out, and I thought we had a disclaimer on the site but I can't find one. Interacting with someone else who's wearing a "well-fitting, well-sealed N95 respirator" isn't actually 10x safer if theirs has a valve.

**Comment by blanchardjeremy** [comment]
It would be great if we could provide a link to an article or an image of what the valves can look like, so people know what they are looking for. (I don't even know exactly what kind of valves I would be looking for vs ones that are filtering.)

**Comment by Telofy** [comment]
When I wear a KN95 mask without valve or with closed valve, the pressure of the air I’m breathing out invariably pushes the mask a bit away from my face so that a lot of the air escapes from around the mask. Some of it goes upward, which seems worse than the downward direction that you get with a valve.

This is a bit first-principle-y, actual studies on this would be better, but for better or worse, the valve question doesn’t seem so decisive to me. I’m highly unsure about this of course!

**Comment by jy2wong** [comment]
"No mask no valve no beard" in the calculator. Valves and how to cover them are covered here https://www.microcovid.org/blog/masks#well-fitting-n95-masks-with-head-straps
