### ISSUE TITLE
PCR test required to fly

### ISSUE THREAD

**Issue by rabourn** [microcovid/microcovid#534]
Would be great to differentiate flights where negative PCR tests are required to board versus not required. Although it won't prevent all those who are contagious from boarding I assume it has some impact on likelihood and it would be great to factor it in.

**Comment by beshaya** [comment]
Thanks for the interest! We're looking into adding an option for testing.

We've also got a blog post about negative PCR tests coming out soon. The short answer is, if everyone gets tested 2 days before the flight and gets the results back before flying, the risk is reduced to 3/4.

If everyone got a rapid test the day of the flight, the risk is reduced to 1/2.

(PCR tests are terrible for knowing if someone is currently infectious because of their long turnaround time and lag time).

**Comment by beshaya** [comment]
(Also, I'm not familiar with these flights! I had heard of countries that require negative results _when you land_  but not flights that require negative tests to board. Which airlines are doing them?)

**Comment by rabourn** [comment]
The two airlines of the UAE require them. I’m about to fly Emirates so I’ll walk to a clinic across the street this morning for a PCR test and I’ll have the results tomorrow night. The test must be taken taken 96 hours before boarding. There’s another location my friend who has to be tested regularly goes to get a PCR test and he gets his results same day. I’m not in that much of a hurry so next day is fine with me.

**Comment by beshaya** [comment]
HI @rabourn, here's our analysis of this: https://www.microcovid.org/blog/negativetests

**Comment by beshaya** [comment]
Marking this as closed.
