### ISSUE TITLE
Localize feet / meter distance units based on country

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#586]
I think we could automatically determine whether to display "6ft+" or "2m+" in the distance dropdown based on what country the person is visiting from.

Reference: https://www.statista.com/chart/18300/countries-using-the-metric-or-the-imperial-system/

**Comment by blanchardjeremy** [comment]
This is a follow on from #583 and #585

**Comment by gyp** [comment]
I don't think this could or should be done better than it is already done.

Measurement units are one of the more finicky details of localization and should be covered by the same process. And they already are, translations in languages where the speaker base overwhelmingly uses metric just use meters (eg. see the [French one](https://github.com/microcovid/microcovid/blob/220708e630efc8c2dc6f221f0a313135d187b62b/src/locales/fr.json#L167)). The problem is that there's no clear unit preference for English speakers, especially as it's a fallback language. US provides a huge userbase and there imperial units will be understood better, while English speakers in the rest of the world would mostly prefer metric. Hence the dual use of "6ft / 2m" in the English locale. A classic solution for this is to have multiple English locales, eg "en-US", "en-UK", "en-CA", "en-IN" and units could be different in those, but I think maintaining those would be an overkill for a project of this size and I'd be strongly against it because of the overhead it introduces.

As for autodetection, we already use https://github.com/i18next/i18next-browser-languageDetector with its default settings that I think does a great job a figuring out the right locale to use based on, with descending order of priority:

1. explicit choice in the URL (chosen from the language selector dropdown or bookmarked or sent over)
2. previous selection stored in cookie and local storage
3. user preference set in the browser (which is much more reliable than source IP checks)

All in all, my vote would be for closing this issue as what could be done here is already done, but I might be missing something.

**Comment by blanchardjeremy** [comment]
Makes total sense to me! Thanks for laying it out so clearly.
