### ISSUE TITLE
"Details" message disappears at wrong time.

### ISSUE THREAD

**Issue by mattbell** [microcovid/microcovid#628]
When you select "Select Location" the "Details" piece also shows the manual entry amounts.

When you select "Enter Data Manually" the "Details" section disappears.  

I'm guessing these are related.

**Comment by jy2wong** [comment]
(1) is addressed by hiding details when going from location -> manual. Chances are if you clicked that button, you just wanted to go back to what was on the screen before.

(2) happens because the details for location mode *are* the things you are directly modifying in manual entry mode. It's not particularly clear that they are the same thing without doing a direct comparison.

**Comment by blanchardjeremy** [comment]
Given that, is this ready to be closed? 

I think so.

**Comment by beshaya** [comment]
Looks good to me.
