### ISSUE TITLE
[Spreadsheet 2.0] Double counting of location differential? 

### ISSUE THREAD

**Issue by linesarefuzzy** [microcovid/microcovid#653]
With great humility and admiration for your spreadsheet mastery, I think I may have found a bug in your formulas. It seems the "PERSON RISK EACH" column on both the Activity Log and Custom People sheets multiplies the result of the `VLOOKUP` by the ratio of the prevalence in the given location with the prevalence in the default location. I believe the purpose of that is to adjust the values from the "Person Risk type / name" table in the `INTERNAL_PERSON` sheet, which draw from the default location. However, for any profile in the Custom People sheet, including most of the preset profiles, I believe the location differential has already been accounted for by the same "PERSON RISK EACH" formula, and it seems it's being double counted. For custom people whose activities reference other custom people, it may be triple counting, and so on. If I'm misunderstanding the purpose of multiplying by that ratio, please correct me!

**Comment by blanchardjeremy** [comment]
@linesarefuzzy First off, a huge THANK YOU for all the suggestions, bug reports, and feature suggestions you've given in the past couple of weeks. I'm REALLY close to launching v2 of the spreadsheet (see #626) and this is a really useful time to get fixes in!

And yes, this is definitely a bug that's present. I hadn't thought to account for it! 

Here's a proposed solution. I'd love your thoughts:

What if, for any custom person type you create that you want to vary with location, you put the word `Varies` in the name. Then it will scale. Like if you want to model a standard "bodyworker" or "hair stylist." And you wanted to be able to make it vary by location so you could use it in multiple situations, you could name it "Bodyworker (varies)" or "Hair stylist (varies)"

"Varies" is probably a pretty opaque keyword to use. Any ideas for a better one?

Thoughts on this approach?

**Comment by blanchardjeremy** [comment]
Okay I have a version of this implemented with the keyword "varies" but we could easily change it once we have something better.

**Comment by linesarefuzzy** [comment]
In the interest of having the formulas be easier to inspect and understand, my inclination would be to add columns to the "Person Risk type / name" table for each custom location, which would also obviate the need for the "Does NOT vary with location" checkbox. Or, perhaps a more elegant solution would be to move the "Avg local resident" definitions from that table to the Locations sheet (transposed to columns), and revise the formulas to look for them there. Both of these options sound like a significant amount of work, though.

**Comment by blanchardjeremy** [comment]
You said
> add columns to the "Person Risk type / name" table for each custom location

Did you mean:
> add columns to the "Person Risk type / name" table for each custom **person**

If you mean custom location, then I'm going to need a lot more explanation of what you're envisioning. 

If you mean custom person, then what I'm envisioning is basically an extra column in the Custom Person sheet that is "Is this a location-independent Custom Person Profile?" with a checkbox.

That sounds like a MUCH better solution than a silly keyword. Haha.

**Comment by linesarefuzzy** [comment]
No, I meant location. If I understand correctly, the reason to multiply by the ratio of the location prevalences is because we're calculating the

**Comment by blanchardjeremy** [comment]
Hmmm. I think I understand you're idea/question about this. 

I think there are more use cases than just "average person in your area"

Here are some use cases that should be able to be location-dependent when they are ultimately used in any Custom Person modeling or your own Activity Log

* Avg local person
* Healthcare worker
* Avg local person works from home
* Generic bodyworker: You could model a bodyworker who sees clients 20 hours/week who are average local residents, then has a certain amount of risk outside of work. (We've done this in our house). Then, anytime you're modeling a person (or your own activity), you can select a location for where the bodyworker is, and it should scale.
* Generic hairstylist: Same as body
* "Lowest possible risk" (set to 1/100th of the avg local person)

Examples of thing that should not vary by location

* My friend Sam
* Any particular individual who doesn't represent a generic profile


Given those examples above, I don't think the solution you proposed will work. Because it doesn't seem to account for things like a "generic custom person" profile. If I'm misunderstanding your point, please let me know. :)

**Comment by linesarefuzzy** [comment]
You're right, my solution would not make it easy to add a location-dependent custom person defined by activities. The location-dependent people that are a simple calculation from the average person (healthcare worker, person who works from home, lowest possible risk) would simply be additional columns in the locations table. But if you wanted to model out a person from their actual activities and also have it vary by location, it wouldn't be straightforward. I don't really get the need for that, and my intuition is that it's not common enough to be worth the extra complication, but if it's important to you I'll take your word for it.

**Comment by blanchardjeremy** [comment]
Yeah it definitely is an edge case I'm describing. 

I'm still having trouble grocking what your proposal is. Can you mock up the user experience under your proposal?

For example, I'm not clear if your proposal involves changing the list of Persom Type. Would it have additional enrtries for each location? So if you had 10 locations you'd have 10 "avg people"? And then we'd just remove the location column from the activity log?

Let me know

**Comment by blanchardjeremy** [comment]
Okay, I implemented a solution: 
![image](https://user-images.githubusercontent.com/32290/105570355-ad5d8280-5cfd-11eb-8b3d-0ab4aad8a38e.png)

**Comment by linesarefuzzy** [comment]
The user experience would basically be the same as it is now; the difference would be that the formulas would be a bit simpler and easier to understand. I'm not sure that difference is significant enough to be worth the effort to make the change if you've already got it working the other way. But yes, if you had 10 locations there would be 10 "avg people." Either by adding each location as a column to the "Person Risk type / name" table, or kind of transposing that table and appending it to the existing location table. But either way would mean a significant change to the "PERSON RISK EACH" formula. You might for example do a VLOOKUP to find the location row combined with an HLOOKUP to find the profile column. And it might mean you'd have to look up the standard location-dependent profiles in a different place or at least in a slightly different way than the custom activity-based profiles.

**Comment by blanchardjeremy** [comment]
Yeah. Got it. I can definitely see that approach having some sense behind it. It makes the person list very long if you have a lot of people. But it leads to less confusion because they would not longer see the "location" column, which confuses folks.

And I think it's probably not worth the effort at this point. 

I'll close this for now and come back to it down the line if we get a bunch of user feedback on this point.

Thanks for talking it through with me!
