### ISSUE TITLE
Consider restoring the essential worker Person information or an equivalent

### ISSUE THREAD

**Issue by pde** [microcovid/microcovid#739]
It seems the frontline/essential worker category was recently removed from the site?

I realise that for some people there may be legitimate group-care reasons to have pushed for removal. But in trying to help someone evaluate the risk of (eg) getting a haircut, or deciding between the in-person and remote versions of various services, that factor is pretty relevant and unavoidable.

I wonder if there's a way of reintroducing it without as much potential for additional psychological burdens on frontline workers?

For instance, adding a setting "indoor business", that's higher risk than merely indoors?

**Comment by beshaya** [comment]
Hi @pde,

While concern over social harm was the reason we re-visited this multiplier, it is not the reason we removed it. We removed it because we couldn't find sufficient evidence that essential workers were any more risky than non-essential workers post autumn 2020. If you'd like to help us gather research on this topic, we'd be happy to review it and see if it is compelling.

Using microCOVID on a hairdresser suggests that cutting hair 40 hours per week yields a risk of about 1/4 of an average person: https://www.microcovid.org/?distance=close&duration=2400&interaction=workplace&personCount=1&riskBudget=1000&riskProfile=average&setting=indoor&subLocation=US_06001&theirMask=surgical&topLocation=US_06&voice=silent&yourMask=surgical

The 3x multiplier for essential workers also creates a contradiction; we estimate 1/3 of all Americans have been infected at this point:
![image](https://user-images.githubusercontent.com/5877421/108433492-f0c2e800-71fa-11eb-8d2d-08943148407a.png)

If essential workers _were_ 3x more likely to be infected, then ~100% of them should have been infected by now. In that case, we'd expect them to be [10x less likely to catch covid (a second time)](https://www.nejm.org/doi/full/10.1056/NEJMoa2034545), so they would actually 3 * 0.1 = 0.3x as risky as an average person.

In general, if a group were X times as likely to contract covid as average, X * 0.27 of them would have had COVID, so now they are (1 - X * .27 * .9) * X) = X - X^2 * .243 as likely to get COVID again. In other words, groups that were more likely to get COVID.

Plotting this shows that any group that had a consistent X over the entire pandemic is no more risky than average (and the worst case scenario, consistently exposed to 2x average risk, yields about average risk):
![image](https://user-images.githubusercontent.com/5877421/108433690-32ec2980-71fb-11eb-8949-3f8420930306.png)

Which indicates that people who have changed their risk profile are the ones who are, by-and-large, getting infected.

Of course, a variant of COVID that is effective at immune escape would ruin the 0.9.

**Comment by pde** [comment]
Just saw this note. Will keep an eye out for literature on this. As an aside, probabilities don't multiply in the way you described, and I believe risks can only be defined relative to a particular unit of time (say, a day or a year). If we think the daily risk y to frontline workers is 3x that of others, y = 3x, your "one third" observation can be written down as s_x := probability of not getting covid =  (1 - x)^(number of days) = 1 - 0.33. Given that observation, solve for s_y.

Running those numbers assuming number of days = 365, I get s_y = 0.29, so about 70% of frontline workers in the US would have had covid if their daily risk was 3x higher.

**Comment by beshaya** [comment]
Good point about running into territory where adding probabilities creates
a large error. You could build an even better model by solving for the
difference equation where each day the proportion of the population that is
immune is the integral of the expected number of cases.
