### ISSUE TITLE
Removal of healthcare worker category is inconsistent with providing the best estimate based on available evidence

### ISSUE THREAD

**Issue by hmrm** [microcovid/microcovid#754]
Re: #718, which I just noticed after I had my first contact with a non-pod human being in two weeks and went over to the calculator so I could put it in my spreadsheet.

Per the disclaimer "In this tool we state our best estimate based on available evidence, even when that evidence is not conclusive". In the Q&A, the removal of the healthcare worker category is justified by the following, all of which are invalid given the disclaimer:

> 1. These studies include data early in the pandemic when COVID-19 was poorly understood and good PPE was unavailable.
> 2. It appears that the average person has become significantly riskier since early in the pandemic (more social activity / less lockdown yields high overall rates).

Both of these are just saying that the "evidence is not conclusive" which is not a valid reason to remove the categorization.

> 3. These categories of people are highly heterogenious. Lumping them all together makes no sense.

The referenced Washington state study (https://www.doh.wa.gov/Portals/1/Documents/1600/coronavirus/IndustrySectorReport.pdf) indicates that healthcare workers had twice the incidence of COVID-19 as other groups. If I have no other information about a healthcare worker that I need to come into contact with (as is often the case when one needs to go to the doctor), I think it's pretty clear that the "best estimate" has to be twice what I'd give to someone else. 

I do not understand how you can simultaneously cite the Washington state report for the assertion that "people who work outside the home got COVID at about the average rate for the state" while ignoring its data on healthcare workers. Nor do I understand why the microcovid project is prioritizing removing categories that would cause people to be more conservative in the activities they take part in. What is the motivation behind these changes?

I am deeply concerned that removing this shortly after removing the essential worker category (#596, #739) indicates the microcovid project is putting other concerns (that I do not understand whatsoever) ahead of evidence-based caution, and can no longer be trusted as a method of measuring and limiting my risk. What am I missing that would restore my confidence in this tool? Why are these changes being made?

Why do I care: I'm currently in a pod that is keeping a .1% risk level, and I'm going into the hospital for some tests next week. I need to decide whether I should isolate from the rest of my pod for a couple of weeks after that, or whether it fits inside budget and I can continue as normal, and a factor of two change in the risk I'll be estimating makes a big impact on that decision. (I obviously can't use the advanced method on random people in the hospital who I don't know).

**Comment by catherio** [comment]
Hey - just speaking purely personally on this one (not that this is "the opinion of the project", but noting I was one of the voices weighing in personally on the team's decision here).

I feel very strongly as you do that we ought to state everything that we truly believe and can get behind, even if that's inconvenient for someone — so, when we really believed that HCWs were 2x the risk of the general population, we said that. Even though that meant some HCWs were experiencing social ostracism from housemates and friends. If we stand by something factually, we stand by it.

However, I actually, personally, just _don't_ truly believe the 2x number anymore. OneMedical employees are getting sick at substantially _lower_ rates than the general population. _None_ of the employees at my dentist has gotten COVID at all, which seems wild to me. Something is going on here with HCW infection rates that I don't understand, and I can't fully account for it. Is it that there's now adequate PPE for everyone, and the higher rates were before that happened? Are there some subgroups of HCWs that have very stringent social norms around actually wearing their PPE, and some that don't? I really just feel basically confused.

In this tool, I try to make sure we're stating things that  _I really believe_. And, yeah, I don't actually believe that we know what's up with HCWs anymore.

This is similar to how we've _never_ said anything about kids and schools, even though people really want us to. We just can't actually figure out what's going on to our satisfaction.

So, it's true we revisited this because we were getting complaints that it was socially inconvenient for people, and so they were asking us "is this really true?". I strongly agree that inconvenience on its own isn't even remotely a valid reason to remove something if we still "buy" it. But in this case, as with schools, we no longer feel that we can figure out what's going on in a way we stand by. So, we stepped back from what felt to me like an "overextended" position of no-longer-firm-enough epistemic confidence.

Hope that makes sense.

**Comment by catherio** [comment]
Oh! I should also add. In the US and many other places, HCWs are now getting vaccinated in large numbers, so estimating them as higher risk felt especially outdated (invalidated) in light of that change coming through.

**Comment by beshaya** [comment]
I would go so far as to say that there is overwhelming evidence that Healthcare Workers are _not_ being infected at 2x or more the average rate. With a state seroprevalence of over 35%, that would require more than 70% of all Healthcare Workers to have been infected. This simply doesn't match the data we are seeing. OneMedical has had single digits of providers infected. A [survey of over 10,000](https://www.acpjournals.org/doi/10.7326/M20-7145) HCW's in Georgia found just 3.8% seroprevalence through June, less than 1/2 the general population's seroprevalence. This seems to sufficiently contradict the hypothesis that HCW's are infected at 2x the regional average.

Separately, I think looking for a classifier for HCW's (or any other broad, poorly defined group) is bad practice unless you have a really solid reason to think the group is homogenous. Contact tracers are telling us that most transmission is happening at grocery stores and in homes now, neither of which are correlated with being a HCW. Likewise, we removed the "discount" for working from home because so many people who work from home were getting infected (again, grocery stores, travel, and social contact).

**Comment by beshaya** [comment]
Oh, worth mentioning, you can still do a decent Advanced Method based on what you see in the office - how many patients are in the waiting room at any given time? How far away are they? What masks do the doctors wear? Are there HEPA filters running? Do they check for symptoms when you come in? Multiply by 40 hours per week and you get a sense for how many microCOVIDs the job is.

**Comment by hmrm** [comment]
Thanks @catherio and @beshaya for the speedy responses! I am very satisfied with the responses to the questions in my later paragraphs.

Re: "With a state seroprevalence of over 35%, that would require more than 70% of all Healthcare Workers to have been infected.", I'm not entirely sure that I follow. Reading the Washington State data, it looks like healthcare workers are described by the following line:

| Industry Sector | Count | Percent | Percent WA employed population |
|-|-|-|-|
Health Care and Social Assistance | 7279 | 25% | 13%

Which seems like a pretty clear ~2x indicator. What am I missing here?

Re: vaccination: In particular the point about vaccination is well taken. I look forward to what you come up with when you complete your vaccine deep dive. 

Re: advanced method: I'm more skeptical about my ability to estimate the advanced method. My experience has been that people will often take off their mask at inopportune moments, particularly when talking, which is more likely to occur in the exam room, and would both significantly impact microcovids and be impossible for me to observe. In addition, given my relative lack of knowledge of what medical work entails and looks like on a day-to-day basis, I would be deeply skeptical of my ability to accurately estimate. My lack of confidence on this front is compounded by my utter inability to understand how the average person could possibly get to ~2000 microcovids over less than two weeks, 10x what I've accrued in five months, which would likely lead me to underestimate due to consensus-bias-esque effects. By my current level of risk aversion, I would like to avoid anything that leads to even close to 50% risk of underestimation.

Re: "it's true we revisited this because we were getting complaints that it was socially inconvenient for people": this makes more sense; I was honestly baffled as to why you'd even be inspired to make these changes. It may be that my severely circumscribed lifestyle has diverged significantly enough from the target audience that the level of risk-aversion of the project, while fully valid and driving towards the good for the target audience, no longer suits my needs.

I'll leave this open as I think my worries about simultaneously using and ignoring the WA study are not fully addressed, but consider my other worries extremely well taken care of. Thanks!

**Comment by beshaya** [comment]
So here's my list of grievances with the Washington state report:
* It is based on confirmed PCR tests, early in the pandemic. During that time, PCR testing was so limited that we think somewhere between 4/5 and 9/10 people with covid couldn't get a test. Tests were prioritized for healthcare workers. So there was a huge bias towards testing HCW's. This easily dwarfs an effect of 2x, and was not controlled for.
* It is based on cumulative cases during a time when behavior likely was vastly different from what it is now - during the early months of the pandemic, everyone thought that COVID was transmitted via large particles and poor hand hygiene. Data in that study would reflect different precautions among HCW's than is common now.
* It doesn't actually cite absolute numbers - it says that 25% of cases among all the workers surveyed were Health Care and Social Assistance workers, but we don't know how many total cases that represents, nor what the error bars are.
* It is in Washington State, which may not reflect the reality in any other state. States have had radically different access to PPE, legislation, and procedures. Extrapolating from one state to another is sketchy at best, unless you have at least a few data points from other states saying the same thing.
* It states that it is missing employment data for 52% (!!) of COVID cases and makes no attempt to control for this.
* It is not a scientific paper, nor is it peer reviewed. 

In summary, the Washington State report shows that HCW's tested positive twice as other groups for whom employment data was available often during a time when testing strategies and precautions were radically different than they are now. They do not attempt to control for any of these factors. Data from other states at other times using more robust methodologies (seroprevalence) and larger sample sizes found very different results (HCW's infected at 1/2 the regional average).

Re: masks, yes absolutely, people take off their masks. However, our 1/8 multiplier for N95 masks is based on risk-reduction from real-world usage among healthcare workers in SARS-CoV-1 wards (as opposed to the measured filtration efficiency or perfect use), which says to me that the multiplier is as close to tailor made for HCW's in SARS-CoV-2 situations as we can get. We believe that the true perfect use multiplier for N95 masks is somewhere between 1/10 and 1/20.

Re: vaccinations - https://www.microcovid.org/paper/14-research-sources#vaccines

**Comment by hmrm** [comment]
I think the vaccinations link covers this issue, although I'll note my continued skepticism that the washington state report is simultaneously good evidence that essential workers are no more risky than average and also bad evidence that healthcare workers are twice as risky as average. Seems like having one's cake and eating it too.

**Comment by beshaya** [comment]
> I'll note my continued skepticism that the washington state report is
simultaneously good evidence that essential workers are no more risky than
average and also bad evidence that healthcare workers are twice as risky as
average.

That's a good point. We really ought to drop that paper from the essential
workers explanation as well. Essential workers are confusing, there just
isn't great data (that we can find) for them. The original multiplier was
based on a small study of people in the SF Mission, taking a snapshot in
time early in the pandemic. This actually made sense for the original
microCOVID calculation to use, since microCOVID was literally designed for
a group of people living in the Mission.

However, extrapolating from the SF Mission in the spring to everywhere in
the world is... sketchy. Additionally, if the original 3x multiplier were
true over the pandemic to date, then 100% of essential workers should have
been infected by now. So either the 3x multiplier is too high, or every
essential worker has been infected (in which case studies on immunity show
they should be 90% less likely to catch COVID for 6 months), in which case
the 3x multiplier is still wrong. I'd be curious to see more detailed data
on this, but it doesn't feel like a priority to go hunting.
