### ISSUE TITLE
Risk Profile for Vaccinated people in Calculator

### ISSUE THREAD

**Issue by hmrm** [microcovid/microcovid#808]
I and my pod are interacting with several people who are fully vaccinated, but who we cannot get a reliable activity log from. It would be extremely helpful to have an "average vaccinated person in your area" option.

**Comment by beshaya** [comment]
We've had a lot of discussions on this topic and unfortunately concluded there isn't a epistemically sound way to get a number for "average vaccinated person" with the data we have.

Consider:
* If 1% of the population of your area is vaccinated, you might think that the vaccinated people are 80% safer than average. That doesn't necessarily hold, because they know they are vaccinated, which may change their behavior (for instance, eating indoors in a crowded restaurant once or twice per week would negate the benefit from being vaccinated).

Worse:
* if 99% of the population of your area is vaccinated, the "average" person is vaccinated, so there is nearly no bonus for being vaccinated. In fact, there may be a *penalty* for being unvaccinated, since the average unvaccinated person is more susceptible to getting covid than the average person (who is vaccinated)

Our suggestion is to use the Risk Tracker, which has been updated to support vaccines for Custom People. If you have a vague sense of the person's weekly behaviors, you can likely build a better model than "average."

If you truly know nothing about the person's behaviors except that they're vaccinated, we acknowledge that they are perhaps, on average, safer, but couldn't put a number on it. If your pod wants to be less conservative, you can certainly do that, but we don't feel comfortable putting a number on this given the uncertainty.

**Comment by hmrm** [comment]
While I can see that there's uncertainty, surely it's possible to have a best estimate?

It seems odd to have microcovid as the singular outlier among the health guidance in saying that one needs to be exactly as cautious around vaccinated people as unvaccinated people when sources such as the CDC are condoning unmasked indoor gatherings with them.

**Comment by blanchardjeremy** [comment]
@hmrm  It's an understandable question. For any paritcular person you're seeing, YES, you absolutely can adjust your behavior with them. That's what the Risk Tracker allows you to do: model their activities over the last 10 days, and mark whether they are vaccinated. 

Would that help address your situation?

If not, can you tell us more about the "average vaccinated person in your area" scenario? Who specifically are you seeing? And can you tell us how you know they are "average" and "vaccinated" but don't know anything else about them?

**Comment by hmrm** [comment]
Unfortunately I cannot accurately (or adequately conservatively) model their activities over the past 10 days. With this particular individual, an elderly relative, there's a lot of shame around any flaunting of pandemic guidance, and therefore particularly risky activities are often omitted from discussion (only to be discovered later). This is not unique; I've had the same problem before with other members of my community.

This interacts poorly with the fact that a single indoors meal at a restaurant has an immense impact on one's risk profile. If one accepted at face value the activities they've told us about doing as representative, they would have a very low number of microcovids, but there has already been evidence that these reports are likely underrepresenting their microcovids, but it's very hard to say how much. Putting a number on the chance that they have gone to a restaurant seems less likely to be accurate than treating it as fully unknown and putting them at some average risk level given the information that I do have, which is that they have fully received one of the mRNA vaccines.

I think this tendency to under-report risky activities may be extremely common in micro-cultures such as mine where there's immense social pressure to take all possible COVID mitigations, as I've seen it in multiple people throughout the pandemic. Because of that, I'm very skeptical of any plan that involves guessing the activities of people who are not keeping a log.

**Comment by beshaya** [comment]
I definitely hear your frustration around trying to figure out how to model
this relative.

IMO, knowing that they are prone to doing risky things and not telling you
about them makes using "average" to describe them kind of sketchy. The
"average" category needs to be amortized over many people about whom you
know the same amount. For instance, when I go to the grocery store than any
individual may be 10x riskier than average, but I'll be doing the same
activity (passing briefly in a store) with hundreds of people over the
course of the pandemic so in expectation it ends up regressing to the mean.

Here's what I'd do:
Use the risk tracker to build two models for this person. One is what they
say they are doing, the other is an intentional overestimate of what they
might potentially be doing (i.e. "they're probably not eating out MORE than
X times per week, probably not going to more than Y indoor gatherings with
Z people). The truth will probably be in between. Then you figure out how
much of the possible range is ok for you (maybe you're ok with the average
of these two scenarios, and that's your estimate). Perhaps you're willing
to take the risk that the relative is all the way at the high end. Possibly
low case rates + a good vaccine means that you'd feel safe even if your
relative were doing things that would have been reckless a few months ago.

**Comment by hmrm** [comment]
I deeply appreciate your helping me out with this (and all the work you all continue to do on the microcovid project, which has made my life immeasurably better over the past six months). Apologies if I'm being obtuse, but I feel like we're talking past each other, so I'm going to go into a bit more depth in the hope that that makes things a bit clearer. I think our core confusion is one of principle rather than this concrete example, specifically:

I believe that any estimate or upper bound I (or any other similarly situated person) make of other people's activities will be a product of my own biases and assumptions, and will bear little relation to any reality of their actual activities or risk.

Let's look at the process I would use for making such an estimate or upper bound: my baseline is going to be the activities of either me or someone else I know who has been logging. Alternatively, I could start with the activities that they've mentioned taking part in, and guess how often they occur per week, which would lead to a remarkably similar number of baseline microcovids compared to the former method. Then I can add a healthy cushion on top of that of activities they haven't mentioned doing, but seem to me within the realm of conceivability, amounting to maybe 10x the microcovids I had at the baseline.

The problem is that I, and the rest of my pod, have been immensely blessed with the ability to maintain a yearly risk level of <.1%. My realm of "reasonable conceivability" doesn't extend to the microcovids of an average person, which is >100x my baseline. If my estimates were accurate enough to be worth using, we wouldn't have a pandemic. I think this likely extends to almost anyone operating at the .1% risk threshold, as we will all have a fairly useless frame of reference.

To pull it back to the concrete example: my intuition is that there's a ~10 percent chance that they ate indoors at a restaurant in the last 10 days, but, when it comes down to it, that's based on literally nothing. I don't know anyone who has admitted to having a meal indoors in a restaurant in the last year, or even discussed doing so out loud, and have no basis for any estimate of how likely anyone would be to do so. With the vaccine, even if they did eat indoors at a restaurant once in the week, that only accrues ~300 microcovids, so they still wind up looking extremely safe compared with the average person, but why am I assuming they didn't do so twice? I think the better approach is to say "I have no meaningful idea what their activities are, so the center of the probability distribution is that they're an average person-who-has-been-vaccinated".

To be clear though, this is not a case of just a single person. There are members of my pod who are now vaccinated, and they are getting increasingly many invitations for various social gatherings with other vaccinated people, most of whom we have even less context for than for my relative.

Hopefully this makes my use-case more clear, and elucidates why estimating (or upper-bounding) activities is not a solution. Let me know if I'm missing something and there's a sound methodology I could use to solve this issue. Thanks again for all the help with this, and apologies for the extended back-and-forth.

**Comment by beshaya** [comment]
Perhaps this might help - the lower bound on an average person is the
regional prevalence times the vaccine multiplier. So in SF, the prevalence
is .05% = 500microCOVID. The vaccine multiplier is 0.2, so the average
vaccinated person is probably between 100 and 500 microCOVID.

You might split the difference and apply the square-root of the vaccine
multiplier, calling them 223.

We're looking at data from Pfizer that suggests revising to a .05
multiplier, so that methodology would yield 111.

I'm kind of curious why your pod uses 0.1% - do you have particularly
vulnerable people you are trying to protect?

**Comment by hmrm** [comment]
> I'm kind of curious why your pod uses 0.1% - do you have particularly
> vulnerable people you are trying to protect?

Yes, we have a member who is extremely elderly and one with a medical condition that would interacts poorly with COVID. They should both be fully vaccinated within a month or so, at which point I anticipate we may re-evaluate (although the course of the pandemic may be very different at that point and it may be unnecessary). However, even were it not for those members, when I was setting up the pod I found that almost all the members (even those without complicating factors) were uncomfortable with a 1% risk level, and it took a bit of convincing to build comfort around a .1% risk level.

**Comment by sagittarian** [comment]
In Israel there are now many activities that are open basically only to vaccinated people. For example, indoor dining is only allowed for people who have been vaccinated, while unvaccinated people can sit outdoors. Since probably 75% of the adult population has been fully vaccinated, I can see that an average vaccinated person is very similar to the average person in general, but I was wondering if it's safer to sit indoors (since then everyone is vaccinated) or outdoors (since the risk of infection is much less outdoors).

**Comment by beshaya** [comment]
Haney:

> Yes, we have a member who is extremely elderly and one with a medical
condition that would interact poorly with COVID. They should both be fully
vaccinated within a month or so, at which point I anticipate we may
re-evaluate

That makes sense. If I were living with someone that matched that
description I would probably hold off on indoor activities with anyone I
didn't have a good model for for at least a little longer; some combination
of your podmates getting vaccinated and prevalence continuing to drop
should get you there. It would be a shame for one of them to get COVID so
close to when they would be vaccinated.

This actually lines up pretty closely the CDC's guidance:
> Visit with unvaccinated people from a single household *who are at low
risk for severe COVID-19 disease* indoors without wearing masks or physical
distancing

Adam:

> I was wondering if it's safer to sit indoors (since then everyone is
vaccinated) or outdoors (since the risk of infection is much less outdoors).

Outside is still probably safer; Israel's data is showing about a 20x
reduction in cases among vaccinated people. Outdoors is probably 20x safer
than indoors, perhaps even more. So if you assume indoors and outdoors are
similar levels of crowded and every single person indoors is vaccinated and
every single person indoors is unvaccinated, the numbers work out about the
same. But consider:
a) some vaccinated people will probably sit outdoors, so the average risk
of a person who is outdoors is a mix of the two groups.
b) If vaccinated people are allowed to do more things / see more people,
they get exposed to more risk and that potentially reduces how much safer
they are than an unvaccinated person (who is presumed to continue being
safe, not eating indoors, etc)

**Comment by anyatche** [comment]
This is an old thread but I want to +1 the request for a risk profile for "person about whom all I know is that they're vaccinated".

Population vaccination levels can and should be accounted for in the math for this, of course. If you know the local vaccination levels and local covid prevalence levels you can calculate an approximate covid prevalence level for each of "local unvaccinated people", "local 2-shot vaccinated people", etc. This does ignore the possibility of risk compensation, but I think it's much better than nothing. (Perhaps there could be a warning saying something like "this assumes vaccinated and unvaccinated people have roughly the same behaviors; you may want to adjust accordingly".)

My main use case is modeling the risk from attending a medium-to-large gathering of vaccinated people; this seems obviously safer than an equivalent gathering of unvaccinated people, or people not filtered by vaccination status; also for a largeish gathering it doesn't really make sense for me to try to model people individually since I don't really know much about them other than that one fact. As a rough estimate I've been manually doing the kind of math I mentioned above based on local vaccination levels, but this is very annoying and it'd be nice to have it automated!

It also would be useful for modeling smaller gatherings with vaccinated people I'm not close enough to to ask a lot of questions about their lifestyle. I realize that's necessarily riskier than meeting with people whose exposure levels I do know things about, but it's still gonna be less risk in expectation than meeting with unvaccinated people, and I'd rather have _some_ way to model this.

**Comment by beshaya** [comment]
I agree that this would be a good feature. I don't have time/energy to make this change, but could help someone who is motivated. Here's what would need to be done:

1 Update update_prevalence.py to pull in vaccination data from covidactnow and jhu.
2 Include this data in the js and csv exports
3 Update calculate.ts to compute the vaccine-adjusted prevalence for average vaccinated people
3 Add fields in the manual prevalence entry to support adding vaccinated %
4 Add a vaccine selector to the "Risk Profile" section in the calculator
5 Add the requisite field to CalculatorData
6 Add logic to calculate.ts to calculate the person's risk (need 3 different formulas depending on if the person is average, fixed value, or calculated by activities)
7 Add tests to calculate_test.ts to demonstrate proper functionality.
8 Figure out how to do all this logic in the Risk Tracker as well.

**Comment by hmrm** [comment]
For the US, ignoring J&J, I think the equations roughly look like:

RA = avg. risk
RV = vaccinated risk
RH = half-vaccinated risk
RU = unvaccinated risk
PV = proportion vaccinated
PH, PU ....



RA = RV * PV + RH * PH + RU * PU
RV = .56 * RH = .1 * RU

->

RA = RV * PV + (RV/.56) * PH ...
RA = .1 * RU * PV + (.1/.56) * RU * PH ...

->

RV = RA / (PV + PH/.56 + PU/.1)
RU = RA / (.1 * PV + (.1/.56) * PH + PU)

Plugging in my local numbers I get multipliers of roughly .16 for vaccinated otherwise-unknowns and 1.6 for unvaccinated otherwise-unknowns.

**Comment by dy9876** [comment]
Hi, new to this - 

If we assume the vaccine multiplier is .2, would choosing a risk profile that's .2 as high yield the same results?

For example, if I'm calculating the risk of a dinner party with vaccinated guests who are average people in my area (3000) but who I know are vaccinated (so 3000 * .2), the risk profile would be .2 of its original number (600)?  Or am I totally missing something?

I respect the hesitancy to put out a sound number, just seeing if there's an easy way to calculate a workaround in the meantime.

**Comment by beshaya** [comment]
Haney, I think there's an error in your derivation:
> RV = .56 * RH = .1 * RU

should be

RV = .1 RU
RH = .56 RU

Then

RA = .1 * RU * PV + .56 * RU * PH + RU * PU

RU = RA / (.1PV + .56PH + PU)

RV = .1RU = RA / (PV + 5.6PH + 10PU)

dy9876 - The formula you list is correct only if approximately no one in
your region has been vaccinated (you can see this by plugging in 0 for PH
and PU above).

You need to know how many people in your region are vaccinated.
Covidactnow.com has this data.

For a 90% effective vaccine,
vaccinated risk profile = average risk profile / (%vaccinated +
%half-vaccinated * 5.6 + 10 * %unvaccinated)

You could simplify a little by ignoring half-vaccinated and use

vaccinated risk profile = average risk profile / (% vaccinated + %
unvaccinated * 10) = average risk profile / (10 - 9 * %vaccinated)

**Comment by beshaya** [comment]
JHU has vaccine breakdowns by type for US & worldwide, but not counties. It al: https://github.com/govex/COVID-19/blob/master/data_tables/vaccine_data/us_data/hourly/vaccine_data_us.csv

covidactnow has vaccine data for US counties, but without type breakdowns: https://apidocs.covidactnow.org/data-definitions/

**Comment by blanchardjeremy** [comment]
@beshaya could you combine those two data sets with the assumption that any individual county matches the national breakdown of vaccine types? Not a perfect assumption, but probably "close enough"?

**Comment by beshaya** [comment]
Sure, yeah, just makes the task larger.

**Comment by blanchardjeremy** [comment]
I mean I'm happy with not doing it that way. I guess I inferred from your last post that you were saying you weren't sure which data set to use.

**Comment by beshaya** [comment]
No, we need both. I'm putting things here as notes to myself.
