### ISSUE TITLE
Q&A: Vaccine protection against severe covid at odds with available evidence?

### ISSUE THREAD

**Issue by TheSven73** [microcovid/microcovid#837]
Microcovid's Q&A suggests that vaccine protection against severe covid (hospitalization or death) is below 100%:

https://github.com/microcovid/microcovid/blob/c6ea542cd401c83e3b71ab28a554464dd3333937/src/posts/paper/13-q-and-a.ts#L215

Is this significantly at odds with the available evidence? For example, [Wikipedia](https://en.wikipedia.org/w/index.php?title=COVID-19_vaccine&oldid=1019606401) lists 100% protection against death or hospitalization for every vaccine, with the possible exception of CoronaVac (ie. Sinovac).
![Wiki_covid_efficacy](https://user-images.githubusercontent.com/853754/115959826-24144280-a4dc-11eb-8bbf-1938381cca4f.png)

[COVID-19 Vaccine AstraZeneca confirms 100% protection against severe disease, hospitalisation and death in the primary analysis of Phase III trials.](https://www.astrazeneca.com/media-centre/press-releases/2021/covid-19-vaccine-astrazeneca-confirms-protection-against-severe-disease-hospitalisation-and-death-in-the-primary-analysis-of-phase-iii-trials.html)

Links to the evidence in question:
[Moderna](https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e0651c7a-2fe2-459d-a766-0d59e919f058)
[Pfizer](https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=908ecbe7-2f1b-42dd-94bf-f917ec3c5af8)
AstraZeneca [one](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7894131) [two](https://www.astrazeneca.com/content/astraz/media-centre/press-releases/2021/azd1222-us-phase-iii-primary-analysis-confirms-safety-and-efficacy.html)
[J&J](https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14a822ff-f353-49f9-a7f2-21424b201e3b)

**Comment by beshaya** [comment]
The lack of confidence intervals on those 100%'s should be immediate red flags - it means the researchers used a statistical tool with incorrect behavior when 0 cases are observed.

All of those studies were too small to tell us what the true rate was. There's now proof that the vaccines are not 100% effective at preventing death from COVID: https://www.mercurynews.com/2021/04/15/cdc-reports-5800-covid-19-infections-74-deaths-in-fully-vaccinated-people/ - that's a 1.2% CFR, which is about what we were seeing before vaccinations (although we expect a higher proportion of vaccinated cases to be asymptomatic, so the true vaccinated CFR may be something like half the unvaccinated CFR.

**Comment by TheSven73** [comment]
That is extremely interesting! That data appears fully consistent with your hypothesis - that the mRNA vaccines are effective mainly at preventing infection, but do not confer any additional protection against severe Covid above and beyond this infection prevention.

I wonder if the same hypothesis holds for the viral vector vaccines? They don't appear to be that effective against (mild) infection. Nevertheless the real-world data from the UK seems very encouraging. I wonder if their very low hospitalisation / fatality rates there can be explained using just AstraZeneca's 60% infection attenuation. Probably significantly less than 60% - they went for a "first doses first" strategy.

**Comment by beshaya** [comment]
> That data appears fully consistent with your hypothesis

In case you're interested in some backstory, that wasn't my original
hypothesis. My original hypothesis was that vaccines should be more
effective at stopping severe disease than symptomatic, but not 100%
(because nothing is ever 100%). But I put very little confidence in this
because I manually computed the CI's for the Phase III studies and saw that
they were totally inconclusive. Israel then released it's paper suggesting
that the additional protection against severe covid was probably 3x or
less. So don't give me too much credit; my hypothesis is merely "the truth
falls within the CI's of published papers, some papers just don't include
correct CI's for their data."

> I wonder if the same hypothesis holds for the viral vector vaccines?

Surprisingly, most of the data I've seen suggests that AstraZeneca's
vaccine has similar efficacy vs hospitalization / death (90%) when compared
to the mRNA vaccines! I have a change in flight to update this.

>The first Pfizer vaccine dose was an estimated 91% effective in reducing
hospitalizations 28 to 34 days later, compared with 88% with the
AstraZeneca vaccine.
https://www.cidrap.umn.edu/news-perspective/2021/04/real-world-studies-find-covid-vaccines-cut-infection-hospitalization

My internal model is that some portion of the human population just can't
be protected against COVID; no matter how "good" a vaccine is, they're in
deep trouble if they get infected. The immune response from the mRNA is so
strong that fewer people get infected at all, but AZ/J&J's vaccines are
still good enough to prevent most of the hospitalizations that are
preventable. This is pure speculation; I have no data for this (indeed, I
can't even think of a study that could prove this).

**Comment by beshaya** [comment]
> My internal model is that the mRNA and VV vaccines both prime the immune system, but each in different ways. 

FWIW, all the vaccines are really quite similar - they cause human muscle cells to produce spike proteins and release them into the blood stream so that immune cells can see them.

Pfizer/Moderna use mRNA for just the spike protein encased in lipid nanoparticles which deliver them into cells.

AstraZeneca has DNA encoding the spike protein added to the genome of a chimpanzee adenovirus (replacing a critical section of the adenovirus's natural DNA which prevents replication)

Sputnik V and J&J are the same as AstraZeneca but using a human adenovirus instead of a chimpanzee.

That is to say, in ALL of the vaccines, when operating correctly, the actual challenge presented to the immune system is identical; spike proteins with identical structure.

So the differences likely come down to how effective the delivery mechanism is at getting into cells, how efficiently muscle cells produce spike protein from the viral genome,  and how strong an immune response the adjuvants (stuff that cause a general immune response, including the virus particles, the lipid nanoparticles, etc) cause.

https://en.wikipedia.org/wiki/Oxford%E2%80%93AstraZeneca_COVID-19_vaccine
https://en.wikipedia.org/wiki/Sputnik_V_COVID-19_vaccine
https://en.wikipedia.org/wiki/Johnson_%26_Johnson_COVID-19_vaccine

**Comment by TheSven73** [comment]
Thanks for the info, appreciate it !

The theory tells us that all vaccines challenge the immune system in an identical fashion. Is that consistent with the observed differences between mRNA and VV immunity? E.g. VV protects much better against severe covid than mild covid, but mRNA does not. Or at least, that's what the data seem to indicate.

**Comment by beshaya** [comment]
> VV protects much better against severe covid than mild covid, but mRNA
does not.

That's one way to read the data. Another is that they all seem to protect
about the *same* against severe COVID*. mRNA seems to protect better
against mild COVID. I wouldn't be surprised if this is actually a dosage /
expression efficiency of the mRNA vaccines (they're more optimized for
production than DNA is); possibly heavier doses of AstraZeneca would be on
par with mRNA against mild COVID. Dosage is something that seems to be a
bit of guesswork / willingness to subject people to side effects. Higher
dosages lead to higher antibody levels, which neutralize COVID before it
has a chance to cause symptoms. They're all sufficient to give the body a
leg up on the virus and avoid severe disease at about the same rate. Also,
if you take the data at face value, Sputnik V is more effective against all
forms of COVID than Pfizer or Moderna, and that's a VV vaccine.

*Pfizer and Moderna are a little better than J&J and AZ for severe COVID,
which I suspect has to do with viral vector immunity (immune system tries
to stop adenovirus but doesn't recognize the nanoparticles used to deliver
the mRNA). Sputnik V ostensibly avoids this by using a different vector for
each injection.

**Comment by beshaya** [comment]
But again, this is all idle musings; my point is there isn't evidence to
say "mRNA is better than VV." That could be true, but there are lots of
other variables we haven't controlled for that could quite easily make up
the difference.

**Comment by TheSven73** [comment]
An interesting [essay](https://www.theinsight.org/p/novelty-means-severity-the-key-to) turned up in Zeynep Tufekci's feed, written by "Dylan H. Morris, a Postdoctoral Researcher at UCLA who studies how the evolution of RNA viruses is shaped by ecological processes within and between hosts."

The essay seems consistent with both our working theories. Broadly:
- Covid's novelty is what makes it dangerous - we have not been primed when we were children
- childhood exposure/infection **or** vaccination as an adult primes the immune system
- primed people can still develop mild symptomatic illness, but are mostly protected from severe symptoms and long covid (which perhaps also includes  the lung damage seen in asymptomatic infections in unvaccinated individuals)
- a small minority fail to mount a proper response to infection or vaccination

The essay also remarks that [the immune system is complicated](https://www.theatlantic.com/health/archive/2020/08/covid-19-immunity-is-the-pandemics-central-mystery/614956/). This leaves plenty of space for both our working theories to co-exist at the moment:
mRNA/VV differences mostly due to
- Ben: dosage ("primes more intensely")
- Sven: dimensional ("primes different aspects")

I guess the mix-and-match trials might indicate which of these two is closer to reality? If mixing VV/mRNA provides better overall protection than mRNA alone, then that would point to dimensional differences. Otherwise, dosage wins.

**Comment by beshaya** [comment]
Definitely agree that the immune system is complicated. There could
absolutely be something different about how the vaccines provoke an immune
response. I just think calling it "mRNA" vs "viral vector" primes our
brains to think about certain things in ways that don't necessarily reflect
reality.

For one, the nomenclature focuses on different parts of the vaccines; to be
more accurate, we should be calling them "nanoparticle vectored spike
protein-encoding mRNA vaccines" vs "adenovirus vectored spike
protein-encoding DNA" vaccines to better highlight the similarities and
differences.

I guess my point is, I consider the vaccines to be the same to first
approximation. Like sending the same blueprints via email or fax. The
blueprints are the most important thing, and that's the same. The steps to
receive it are, to use your phrasing, dimensionally different and can get
screwed up in different ways. Ultimately, if all goes well, you build the
same thing from the blueprint regardless of how it is delivered.

**Comment by beshaya** [comment]
https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(21)00947-8/fulltext

In an observational study of basically the entire 6M population of Israel, Pfizer's vaccine reduced chance of death from COVID by 96.7% (CI 96.0-97.3). At the same time, it was 97.0% (CI 96.7-97.2) effective at preventing symptomatic COVID. 

So actually, Pfizer's vaccine provides almost exactly no protection against severe covid beyond what it provides against symptomatic covid.

**Comment by TheSven73** [comment]
That's really fascinating ! I wonder what the data on the VV vaccines will show.

**Comment by TheSven73** [comment]
I guess this data allows for an interesting thought experiment. The US has now (quasi) officially declared the pandemic over, as witnessed by the removal of official restrictions on the fully vaccinated. But the rest of the world isn't there yet by a long shot. Even countries with a high vaccination uptake (such as UK or Canada) are hesitant about opening up, because they are unsure if vaccination will provide herd immunity. And in a world with variants and vaccine hesitancy, that is a very valid question IMHO.

So as a thought experiment, imagine a country opening up with 100% mRNA vaccine uptake. Assume insufficient vaccine efficacy to reach herd immunity. Assume no previous immunity through infection. Covid will grow exponentially.

Given an estimated IFR of 1%, and 1/33 vaccine protection against death, we see that 300 per million will still die.

This compares _very_ favourably against the US or UK lockdown death toll of 2000 per million. Yet for Canada with its 700 per million lockdown deaths, it's quite significant.

I suspect that this consideration might play a significant role in the willingness of a society to re-open. Places with high death toll and high risk tolerance (such as the US) might do so much more readily than risk-averse and low death toll countries such as Canada. In fact, the latter are at risk of being "stuck" with Covid measures indefinitely.

**Comment by TheSven73** [comment]
(obviously these numbers are far too pessimistic, even beyond their pessimistic assumptions - because in reality, exponential growth will stop after herd immunity is reached, which means less than 100% will be infected. but still interesting as an order-of-magnitude estimate)

**Comment by beshaya** [comment]
> So as a thought experiment, imagine a country opening up with 100% mRNA
vaccine uptake.

We don't need to do a thought experiment; Israel did this and recently
published the results:
https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(21)00947-8/fulltext

(side note, they showed almost no protection against death)

> Assume insufficient vaccine efficacy to reach herd immunity. Assume no
previous immunity through infection. Covid will grow exponentially.
> Given an estimated IFR of 1%, and 1/33 vaccine protection against death,
we see that 300 per million will still die.

Hold up, the CFR is 1%. The IFR is lower (CDC
<https://www.cdc.gov/coronavirus/2019-ncov/hcp/planning-scenarios.html>:
500 per million in 18-49 year olds, 6000 for 50-65, 90,000 for 65+). Then
the vaccine makes ~90% people just plain immune, so you get something like
10-100 per million dead. But you don't, because at 100% vaccination you
have herd immunity (demonstrated by Israel).

For reference, the flu killed 34,157 Americans in the 2018-2019 season,
roughly 100 per million.

**Comment by TheSven73** [comment]
Thanks for checking those numbers! When Googling for IFR, I found so many estimates, so I took [this one](https://www.webmd.com/lung/news/20201030/covid-19-infection-fatality-ratio-is-about-one-point-15-percent).

The lower IFR is certainly great news. And so is the "real world proof" that Israel has been able to reach herd immunity.

Israel is basically one point on a (multi-dimensional) surface: 63% fully vaccinated mRNA means you end up on the herd-immunity side of the surface. I wonder if we have more points like this? What kind of estimates can be make at this point?

I am thinking of the current situation in Ontario - 59% have received their first shot, 6% fully vaccinated. 90% mRNA and 10% VV. I am guessing one shot provides decent protection against severe covid. But there is still a lockdown - a stay-at-home-order until yesterday, retail is closed, schools won't re-open until September. Would it be safe to assume that authorities perceive Ontario to be on the "no herd immunity" side of the surface still?

**Comment by beshaya** [comment]
Single doses seem to provide ok protection against severe COVID (maybe
80-90% compared to 96-97% for two doses), but they seem to provide minimal
protection from mild/asymptomatic (maybe 50%). COVID has an R0 somewhere
between 2.5-5, perhaps higher with variants. 50% sterilizing immunity would
yield a reproductive number of 1.25-2.5, which would still allow
exponential growth.

**Comment by TheSven73** [comment]
Exactly! I'm a bit worried about those gi-normous "error bands" on variant infectiousness, R0, vaccine protection from infection, etc.

Herd immunity seems to be a black-and-white thing in the manner of Charles Dickens: "R0=0.99, result happiness. R0=1.01, result misery". I wonder how "close to the edge" Israel finds itself. The closer to the edge, the more likely that new variants cause a Dickensian reversal, no?

**Comment by beshaya** [comment]
Oh, that's true and a thing that keeps me up at night.

Note that R = reproductive number, R0 = reproductive number w/o
intervention, so in Israel we are observing R rather than R0. You can't
directly observe R0 anymore, since no country is doing nothing.

I will say that, if R=1.01, people get infected which results in more
immunity which drops R below 1. Alternatively, you can just keep some of
the highest risk places closed or at limited capacity to exert a small
amount of influence on R. Also, R=0.99 basically means the disease
circulates (basically) forever and everyone eventually gets exposed
(although your hospitals won't be overwhelmed).

You could back calculate Israel's R by fitting an exponential function to
their cases with a time base of the the reproductive time of covid (which I
roughly remember as being 5 days).

**Comment by TheSven73** [comment]
I seem to remember from school that fitting exponential curves in the real world is not very productive. Due to the nature of an exponential, non-linear confounders grow so quickly, that the factor we're trying to fit is super sensitive to the slightest change in input data. So in most case, all you really know is whether the growth factor is positive or negative. Perhaps it does work on the Israel data.

I find all of this quite worrying.

**Comment by beshaya** [comment]
Fitting an exponential curve tells you what R *was*. Assuming that it will
be the same is not very productive, since almost no systems are actually
exponential. But you could get a sense of "oh, R in Israel is 0.5, that's
probably somewhat resilient to behavior changes" or "R is 0.95, the
slightest perterbance could put them back on exponential growth"

**Comment by beshaya** [comment]
Oh! Also, 70% vaccination likely means close to 100% vaccination of people 65+. I was just reading an analysis that showed that in CA, people 65+ are 15% of the population and 10% of cases but 75% of deaths. So vaccinating just that 15% of the population is a huge drop in the maximum number of deaths you'd expect to see even without herd immunity.

**Comment by TheSven73** [comment]
Except in Ontario, where the vaccine hesitancy in 80+ is such that only 70-odd-percent has been vaccinated. A lower percentage than the 18-24 range, apparently...

**Comment by beshaya** [comment]
Well that's somewhat unfortunate.

**Comment by TheSven73** [comment]
This [study](https://www.medrxiv.org/content/10.1101/2021.05.30.21257971v1) suggests that heterologous vaccination (i.e. VV first dose followed by mRNA booster) elicits a better immune response than two mRNA doses alone. Wondering what you make of this.

**Comment by TheSven73** [comment]
> This leaves plenty of space for both our working theories to co-exist at the moment:
> mRNA/VV differences mostly due to
> 
> * Ben: dosage ("primes more intensely")
> * Sven: dimensional ("primes different aspects")
> 
> I guess the mix-and-match trials might indicate which of these two is closer to reality? If mixing VV/mRNA provides better overall protection than mRNA alone, then that would point to dimensional differences. Otherwise, dosage wins.

@beshaya there is now [evidence](https://www.medrxiv.org/content/10.1101/2021.05.30.21257971v1) that heterologous vaccination (1st dose VV, 2nd dose mRNA) elicits a significantly better immune response than two doses of mRNA alone. Does that mean we should now update our priors and attach a higher probability to the "mRNA/VV prime different aspects" hypothesis?
