### ISSUE TITLE
Negative amount of cases being reported for some locations

### ISSUE THREAD

**Issue by evansiroky** [microcovid/microcovid#856]
This is happening on both the web and in the tracker.

<img width="364" alt="Screen Shot 2021-05-24 at 9 19 49 AM" src="https://user-images.githubusercontent.com/3112493/119376894-59de4f80-bc71-11eb-9dd9-0505fb55c2fe.png">

**Comment by blanchardjeremy** [comment]
Hi! Good catch. Yes, this sometimes happens when the John Hopkins source data is off. For some reason, it happens quite a bit with Santa Cruz (or at least, that's where I've seen multiple reports). There's not an easy fix on our side. For now, I just reverted to our prevalence update from a few days ago. And I'll see what happens in the next few days when I do another update.

**Comment by beshaya** [comment]
Thanks so much for catching this, @evansiroky. Fix is in flight.
